services:
  api:
    build:
      context: ./server
    environment:
      - PORT=4000
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "991"
    ports:
      - "4000:4000"
    restart: unless-stopped

  web:
    build:
      context: ./client
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
